version: '3.8'

services:
  db:
    image: postgres:17
    container_name: sc-postgres-db
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sc-member-app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: